name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install Yarn
        run: corepack prepare yarn@stable --activate
        
      - name: Install Dependencies for DB
        working-directory: packages/db
        run: yarn install
        
      - name: Generate Prisma Client
        working-directory: packages/db
        run: yarn db:generate
        
      - name: Install Dependencies
        run: yarn install
        
      - name: Run build
        run: yarn build
        